name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl: ['5.12', '5.20', '5.30', '5.38']
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: sudo apt-get update -qq && sudo apt-get install -qq 7zip
      # Unpack::SevenZip 0.02 (not on CPAN yet)
      - run: cpanm --notest https://github.com/tynovsky/unpack-sevenzip/archive/1e5148d52ff93d49c16024dbe75f527ebc293836.tar.gz
      - run: cpanm --notest --installdeps .
      - run: prove -lv t xt
